### ISSUE TITLE
Deprecated Node modules

### ISSUE THREAD

**Issue by uliska** [electron/electron-api-demos#224]
During the `npm install` step I get warnings about deprecated modules:

* `jade@0.26.3`
* `wrench@1.5.9`

Installing and running works, but maybe this should be addressed.

For the record: I'm running Node 4.4.4 on Debian 8.4

**Comment by jlord** [comment]
These modules are dependencies of projects we don't maintain. 

I've checked and the two projects, `mocha` and `electron-windows-store`, have not yet made these updates in their latest version. 

I'm going to close this out since nothing is broken and it just occurs once when installing locally (people who download the app won't see this) and one day (fingers crossed!) these updates will be upstreamed and they'll go away.
