### ISSUE TITLE
msi is not work in windows 10

### ISSUE THREAD

**Issue by dwtrace** [electron/electron-api-demos#246]
windows 10
node v6.2.1

run :npm run installer  to create msi file。but the .msi file is not work.

After running the interface, it's over
 
![20160718135444](https://cloud.githubusercontent.com/assets/19339005/16906760/3e0abab0-4cef-11e6-8038-54f276e7011c.png)

**Comment by jlord** [comment]
Do you mean that this screen you've included freezes and never concludes building the installer?

**Comment by jlord** [comment]
@dwtrace the `npm run installer` script generates an `ElectronAPIDemosSetup.exe` file, how did you  generate an `msi`?

**Comment by dwtrace** [comment]
change installer.js config: noMsi: false ,then generate an msi file

**Comment by jlord** [comment]
@dwtrace Hmm, I just tried it myself with `noMsi: false` and was able to generate the file and when running it, it did not hang, and completed successfully.

I'm running:

- Windows 10 Pro x64
- Node 6.5.0

Because you've changed the original source code here I'm not sure if this is actually an issue with the Demos app itself.

**Comment by paulcbetts** [comment]
It seems super unlikely that you want to distribute the Electron Demos app in an Enterprise deployment, you almost certainly want the EXE file

**Comment by jlord** [comment]
Since this app isn't supporting/generating `.msi` files, I'm going to close the issue here. 

If you have trouble with `.msi` in your own projects, look for the [Squirrel project](https://github.com/Squirrel) for more resources ✨
