### ISSUE TITLE
Content and navigation structure of the SPA

### ISSUE THREAD

**Issue by Siilwyn** [electron/electron-api-demos#277]
Looking at the overall architecture I'd love to hear some of the motivation behind the decisions of the 'SPA architecture' especially the use of `<template>`'s and navigation interests me.

- What is the benefit of using the template tag if you put all of the content in it? As far as I could see it's useful for structure of HTML you do not want to render immediately, [like this](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template#Example). Splitting things up. But all sections are completely contained within these template tags.
- For the navigation it seems to be all handled in [`nav.js`](https://github.com/electron/electron-api-demos/blob/master/assets/nav.js). How would handling a section/page that is filled dynamically with data by JS prior to showing it fit in this pattern?

I hope I'm clear, just being curious. ^^

**Comment by HudsonAfonso** [comment]
+1

**Comment by Siilwyn** [comment]
@simurai looks like you put up the most code, could you enlighten us? :)

**Comment by simurai** [comment]
I was only involved with the styling, but if I recall correctly, we wanted to replace the content without reloading the page. So that it appears smoother. There would be many options by using a library like React, Vue etc. but the idea was to see if there is a way with "browser APIs" only. So `<template>`'s seemed to work out great.

Same with the styling, instead of using a preprocessor we just used plain CSS. Luckily it's already possible to use custom properties (CSS variables).

That said, for your Electron app you're totally free to use whatever you prefer.

/cc @kevinsawicki @zeke

**Comment by Siilwyn** [comment]
Thank you for your reply simurai! I'm still curious about the `<template>` details and how you would handle dynamic pages.

**Comment by zeke** [comment]
Hi @Siilwyn. Thanks for your curiosity!

> we wanted to replace the content without reloading the page

> the idea was to see if there is a way with "browser APIs" only

☝️  those were the two motivators for using `<template>` tags.

> How would handling a section/page that is filled dynamically with data by JS prior to showing it fit in this pattern?

Building a site that uses `<template>` tags in conjunction with dynamically loaded content would be pretty straightforward. Here's a decent article that outlines a technique for doing just that: http://blog.teamtreehouse.com/creating-reusable-markup-with-the-html-template-element

**Comment by Siilwyn** [comment]
Thank you @zeke and @simurai too of course! ^^
