### ISSUE TITLE
sudo npm i -g electron stop

### ISSUE THREAD

**Issue by i2801** [electron/electron-api-demos#279]
npm v4.0.3
node v6.9.1
------------------------------

> electron@1.4.10 postinstall /usr/local/lib/node_modules/electron
> node install.js

now stopping...

**Comment by MarshallOfSound** [comment]
* You shouldn't really install node modules with `sudo`.  It breaks things, fix the permissions of the folder rather than resorting to `sudo`
* You also shouldn't be installing `electron` globally as it messes with packages.

The issue of `node install.js` not terminating is normally caused by network issues, try disabling VPN's / proxies you may have running or trying a different network
