### ISSUE TITLE
Exception on closing renderer process window

### ISSUE THREAD

**Issue by MegaJ** [electron/electron-api-demos#286]
Linux, elementary OS (Luna)
32 bit
Node v6.9.2

Replication steps:
> Windows > Create and manage windows
> Click "Create a new window"
> Click "View Demo"
> Close the main window
> Close the window opened with "View Demo" with the "x" button OR ctrl + C in terminal

A modal pops up telling of an error in create-window.js on line 9. 

Stack trace: 

Uncaught Exception:
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: create-window.js:9:7.
    at BrowserWindow.callIntoRenderer (/usr/lib/node_modules/electron/dist/resources/electron.asar/browser/rpc-server.js:199:19)
    at emitOne (events.js:96:13)
    at BrowserWindow.emit (events.js:188:7)

I'm not sure why this happens. Sometimes it doesn't do that when I close the main window and let it sit for a while, then close the demo window. I tried to find the cause of this but couldn't figure it out. As a workaround, closing all windows when the main windows seems to make sense for this app:

```javascript
      mainWindow.on('close', function () {
      const allWindows = BrowserWindow.getAllWindows();
      allWindows.forEach(function (window) {
        if (window.id !== mainWindow.id) {
          window.close()
        }
      })
    })
```

Also, when the demo window is the last window and we click on the <a>, the process doesn't end either, causing my shell not to print out a new prompt unless I Ctrl+C on the terminal. I have this problem in my own application so I'm curious as to why this is happening and what a better solution might be.

**Comment by MarshallOfSound** [comment]
Without the relevant code it's hard to point at what is wrong but in general this error.

> Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: create-window.js:9:7.

Means you have an event listener in a renderer process for an event in the main process (such as `remote.getCurrentWindow().on('closed')`) that is being called but the renderer process has been destroyed.  In general this pattern is a bad idea.  If you need an event from the main process you should listen for the event in the main process, fire an IPC event (this is always safe) and listen for the IPC event in the renderer process.

This guarantees that if the renderer process is destroyed the listener in the main process will not throw errors.

The seemingly random nature of this error you are noticing is probably due to a race condition in your own code between a function / event being called and the window closing.

**Comment by MegaJ** [comment]
I might have miscommunicated. The code in question is in this repository, so you have the relevant code. The electron-api-demos has this error/behavior described above.

I appreciate the feedback and I'll go try out your suggestion on my own app! Since I'm new to electron I thought it might be good to structure my own code for window handling like how the api-demos is structured. I think it's likely that other people might do the same.

Do you want to handle this fix, call it a nonissue, or do you want a PR?
