### ISSUE TITLE
Clarificaton on nav

### ISSUE THREAD

**Issue by enricovittorini** [electron/electron-api-demos#448]
* What operating system are you using?
windows 
* What version of Node.js is on your system?

i have created the following cose in ./assets/test.js
```
const t =  function hello() {
    
    console.log("test");
};
module.exports = t;
```

At the beginning of the ./assets/nav.js i put the following line
`const t = require('./assets/test.js')`

when I run the app (npm start) in app debug console i have:

**Uncaught Error: Cannot find module './assets/test.js'**

My goard is to call a function from the Nav when i click on a section link

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
